config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :super_admins
  devise_for :admins
  devise_for :users
  get 'dashboard', to: 'super_admins#dashboard', as: :super_admin_dashboard
  get 'admin_dashboard', to: 'admins#dashboard', as: :admin_dashboard

  get '/service-worker.js', to: 'service_worker#service_worker'
  get '/manifest.json', to: 'service_worker#manifest'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  enum role: { user: 0, teacher: 1, guardian: 2, student: 3 }
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def dashboard; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    case resource
    when User
      root_path
    when SuperAdmin
      super_admin_dashboard_path
    when Admin
      admin_dashboard_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
    # redirect_to super_admin_root_path if current_user.super_admin?
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  protect_from_forgery except: :service_worker
  # skip_before_action :authenticate_user!

  def service_worker; end

  def manifest; end
end

app/controllers/super_admins_controller.rb
class SuperAdminsController < ApplicationController
  before_action :authenticate_super_admin!
  layout 'super_admin'

  def dashboard; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_menu_links(path, icon_class, label)
    content_tag(:li) do
      link_to path, class: 'block px-4 py-2 hover:rounded hover:bg-gray-700' do
        concat content_tag(:i, '', class: "fa-solid #{icon_class} mr-2")
        concat content_tag(:span, label, class: 'hidden md:inline-block')
      end
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/service_worker_helper.rb
module ServiceWorkerHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/dashboard.html.erb
<h1>Admin Dashboard </h1>
<%= button_to 'sign out', destroy_admin_session_path, method: :delete %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Edumanage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta property='og:title' content='Edumanage'/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png'), rel: 'icon', type: 'image/png', sizes: '192x192' %>
    <link rel="apple-touch-icon" sizes="180x180" href="assets/images/apple-touch-icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="manifest" crossorigin="use-credentials" href="/manifest.json" />
  </head>

  <body>
    <main class='flex'>
      <nav class='flex'>
        <article class='w-64 p-4 h-screen bg-gray-600 sticky top-0'>
          <div class='flex items-center gap-3'>
            <%= image_tag('favicon-192x192.png', class: 'w-12', alt: 'edumanage') %>
            <h1 class='text-md py-2 text-white font-bold hidden md:block'>Edumanage</h1>
          </div>
          <%= render 'shared/side_menu_links' %>
        </article>
      </nav>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Edumanage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta property='og:title' content='Edumanage'/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png'), rel: 'icon', type: 'image/png', sizes: '192x192' %>
    <link rel="apple-touch-icon" sizes="180x180" href="assets/images/apple-touch-icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="manifest" crossorigin="use-credentials" href="/manifest.json" />
  </head>

  <body class='p-4'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/super_admin.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Edumanage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta property='og:title' content='Edumanage'/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png'), rel: 'icon', type: 'image/png', sizes: '192x192' %>
    <link rel="apple-touch-icon" sizes="180x180" href="assets/images/apple-touch-icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="manifest" crossorigin="use-credentials" href="/manifest.json" />
  </head>

  <body>
    <main class='flex'>
      <nav class='flex'>
        <article class='w-64 p-4 h-screen bg-gray-600 sticky top-0'>
          <div class='flex items-center gap-3'>
            <%= image_tag('favicon-192x192.png', class: 'w-12', alt: 'edumanage') %>
            <h1 class='text-md py-2 text-white font-bold hidden md:block'>Edumanage</h1>
          </div>
          <%= render 'shared/side_menu_links' %>
        </article>
      </nav>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1>HOME</h1>
<%=icon('fa-brands', 'font-awesome')%>

<% if current_user %>
  <p>Hello, <%= current_user.email %></p>
  <%= link_to 'Profile', edit_user_registration_path %>
  <%= button_to 'log out', destroy_user_session_path, method: :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/service_worker/manifest.json.erb
{
  "short_name": "Edumanage",
  "name": "Edumanage",
  "id": "/",
  "icons": [
    {
      "src": "<%= image_path "edu_manage_logo_512x512.png" %>",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "start_url": "/",
  "background_color": "#fff",
  "display": "standalone",
  "scope": "/",
  "theme_color": "#e8e0fa"
}

app/views/shared/_side_menu_links.html.erb
<ul class='flex flex-col text-gray-50'>
  <% [
      { icon_name: 'gauge-high', label: 'Dashboard', path: super_admin_dashboard_path },
      { icon_name: 'building-columns', label: 'Schools', path: super_admin_dashboard_path },
      { icon_name: 'id-card', label: 'Onboard', path: super_admin_dashboard_path },
      { icon_name: 'gear', label: 'Settings', path: super_admin_dashboard_path },
      { icon_name: 'right-from-bracket', label: 'Sign out', path: super_admin_dashboard_path }
      ].each do |item| %>
    <%= side_menu_links(item[:path], item[:icon_name], item[:label]) %>
  <% end %>
</ul>

app/views/super_admins/dashboard.html.erb
<h1>Super Admin Dashboard</h1>
<%= button_to 'sign out', destroy_super_admin_session_path, method: :delete %>